name: aarch64-unknown-linux-gnu

on:
  workflow_dispatch:
    inputs:
      ffmpeg_ref:
        description: FFmpeg git tag / branch / commit
        required: true
        default: n8.1

jobs:
  build:
    uses: ./.github/workflows/reusable-build-audio-target.yml
    with:
      ffmpeg_ref: ${{ inputs.ffmpeg_ref }}
      target_triple: aarch64-unknown-linux-gnu
      target_os_family: linux
      target_ffmpeg_arch: aarch64
      target_ffmpeg_os: linux
      runner_label: ubuntu-24.04-arm
